server:
    port: 9001

spring:
   application:
      name: dept-service
      
eureka:
    client:
       register-with-eureka: true
       fetch-registry: true
       service-url:
          defaultZone: http://admin:admin@localhost:8761/eureka
    instance:
       hostname: localhost
    server:
       wait-time-in-ms-when-sync-empty: 0